"""
run_local_demo.py -- Real end-to-end pipeline run, no AWS required.

This is the script to run FIRST on your own machine to validate the
whole pipeline before touching AWS at all:

    1. Make sure Qdrant is running:        docker compose up -d
    2. Make sure the spaCy model is installed:
           python -m spacy download en_core_web_sm
    3. Put one or more PDFs in data/sample_pdfs/
       (or run src/ingest/fetch_arxiv.py with --bucket pointed at a
        local path adaptation -- see README for the quick way to grab
        a couple of real arXiv papers without S3)
    4. Run:  python scripts/run_local_demo.py

This exercises the REAL parse.py (unstructured), REAL embed.py
(sentence-transformers), and a REAL local Qdrant instance -- nothing
mocked. If this script runs clean, your core pipeline logic is proven
correct end-to-end, and the only remaining work is wiring it to S3 +
Lambda for automation.
"""

import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from etl.pipeline import process_document  # noqa: E402
from vectorstore.qdrant_client import VectorStore  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

SAMPLE_PDF_DIR = Path(__file__).resolve().parent.parent / "data" / "sample_pdfs"

# Minimal manual metadata for the demo PDF generated by _make_test_pdf.py.
# If you've dropped in real arXiv PDFs instead, you'd normally pull this
# from the *.metadata.json sidecar that fetch_arxiv.py produces -- see
# README for the one-liner to fetch real papers locally.
DEMO_METADATA_BY_FILENAME = {
    "2401.99999_test_paper.pdf": {
        "arxiv_id": "2401.99999",
        "title": "Efficient Retrieval-Augmented Generation via Hierarchical Semantic Chunking",
        "authors": "Jane A. Researcher, Wei Zhang, Carlos M. Ortega",
        "category": "cs.LG",
        "published_date": "2024-01-15",
    }
}


def main() -> None:
    pdf_paths = sorted(SAMPLE_PDF_DIR.glob("*.pdf"))
    if not pdf_paths:
        print(f"No PDFs found in {SAMPLE_PDF_DIR}. Add at least one PDF and re-run.")
        sys.exit(1)

    print(f"Connecting to Qdrant at http://localhost:6333 ...")
    store = VectorStore(url="http://localhost:6333")
    try:
        store.ensure_collection()
    except Exception as e:
        print(f"Could not connect to Qdrant. Is it running? Try: docker compose up -d")
        print(f"Error: {e}")
        sys.exit(1)

    total_chunks = 0
    for pdf_path in pdf_paths:
        metadata = DEMO_METADATA_BY_FILENAME.get(
            pdf_path.name,
            {"arxiv_id": pdf_path.stem, "title": pdf_path.stem},
        )
        n = process_document(pdf_path, document_metadata=metadata, vector_store=store)
        total_chunks += n
        print(f"  {pdf_path.name}: {n} chunks upserted")

    print(f"\nDone. {total_chunks} total chunks upserted.")
    print(f"Collection point count: {store.count()}")
    print(f"\nNext: try scripts/query_demo.py to run a semantic search against this data.")


if __name__ == "__main__":
    main()
